apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: spring-book
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: twotanawin/backend:1.0
        ports:
        - containerPort: 8282
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: spring-book
spec:
  selector:
    app: backend
  ports:
  - port: 8282
    targetPort: 8282
  type: ClusterIP 