apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: gogreen-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: artifactory.wdc.com:6642/frontend:1.5
        ports:
        - containerPort: 3000
    env:
      - name: NEXT_PUBLIC_API_URL
        value: "http://backend-service.gogreen-app.svc.cluster.local:8282"
        envFrom:
        - configMapRef:
            name: app-config
