services:
  spring_book_db:
    image: postgres:16
    container_name: spring_book_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=springbookdb
    ports:
      - "5436:5432"

  spring_book_pgadmin:
    image: dpage/pgadmin4
    container_name: spring_book_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8086:80"
    depends_on:
      - spring_book_db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgadmin_data: